### ISSUE TITLE
Part ways with message-pack

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/lol#130]
lol 0.6.2 uses message pack. The reason is zero-copy decoding. When the backing memory lives long enough, it is obvious that the Bin field of decoded object can be just referencing to it.

MessagePack is nicely designed serialization framework however, my concern is firstly messgepack-rust is not going to be maintained actively (https://github.com/3Hren/msgpack-rust/issues/255) and secondly mixing two frameworks isn't straight forward.

Regarding the zero-copy decoding, prost 0.7 started to support zero-copy decoding:

> @rolftimmermans added support for generating Rust bytes::Bytes fields from protobuf bytes fields. When deserializing from a Bytes instance, this enables zero-copy deserialization for bytes fields!

https://github.com/danburkert/prost/releases/tag/v0.7.0

We can use this instead of message-pack and since Bytes is reference-counted this way is more convenient than referencing because we are free from lifetime stuffs.

Related: https://github.com/hyperium/tonic/issues/517

**Comment by only-cliches** [comment]
If you can use Serde, I'd recommend switching to Bincode instead of Prost.

Bincode is many times faster on decode and encode tasks than Prost with the same message.  [Benchmarks](https://github.com/only-cliches/NoProto#benchmarks).  All fields can be zero copy, including string fields.

**Comment by akiradeveloper** [comment]
@only-cliches Thank you for the information. The benchmarks actually show that Bincode is faster. I am curious about the mechanism (or difference between protocol buffer) so I will look into it. If there exists some document, it would be a great help.

**Comment by akiradeveloper** [comment]
done. https://github.com/akiradeveloper/lol/pull/152
