### ISSUE TITLE
Docker image for lol-admin

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/lol#191]
It would be so nice to have a docker image that contains lol-admin.

**Comment by RishiKumarRay** [comment]
FROM rust:latest
WORKDIR /lol
RUN rustup component add rustfmt
COPY ./ /lol
RUN cargo build --release --bin lol-admin
ENTRYPOINT ["target/release/lol-admin"]

@akiradeveloper is this what you want, i saw the PR took references from it, looks like it is still unmerged can i raise a PR if the above dockerfile is right

**Comment by akiradeveloper** [comment]
@RishiKumarRay I've waited for the current PR to be fixed two weeks but no action's been made so I think you can make a new PR.

The script is almost fine but using multi-stage build to reduce the image size would be much better.

**Comment by akiradeveloper** [comment]
I will remove lol-admin in 0.10
